services:
  - type: web
    name: feastly-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: NODE_DNS_SERVER_1
        value: "8.8.8.8"
      - key: NODE_DNS_SERVER_2
        value: "1.1.1.1"
